### ISSUE TITLE
Funciona en laravel 5.5

### ISSUE THREAD

**Issue by TranceDevCode** [jorgecancinof/laravel-flow#1]
Hola Jorge, me gustaría saber si el paquete funcionara en laravel 5.5 y php 7.0 te consulto porque hace 2 o 4 años no se actualiza el paquete... igual porque la api version de flow ya esta en 3.0.1 te agradecería amigo, muchísimas gracias!

https://www.flow.cl/docs/api.html

**Comment by jorgecancinof** [comment]
La última vez que probé el paquete fue el año pasado (junio de 2018), precisamente con Laravel 5.5.* y PHP >= 7.0, así que debería seguir funcionando. Me comentas qué tal te fue, saludos.
