### ISSUE TITLE
pagina confirmación

### ISSUE THREAD

**Issue by TranceDevCode** [jorgecancinof/laravel-flow#2]
Amigo tengo instalado el paquete flow en mi proyecto pero creando las vistas me doy cuenta que no existe la vista de confirmación, si esta la de fracaso y éxito...

gracias y saludos!

**Comment by jorgecancinof** [comment]
La confirmación no utiliza vistas, solo pasa por el controlador para comunicarse con Flow y saber si la orden fue aceptada o rechazada.
