### ISSUE TITLE
Funciona en laravel 6?

### ISSUE THREAD

**Issue by L3g4ult** [jorgecancinof/laravel-flow#3]
Hola
Queria saber si funciona en laravel 6
cada vez que intento instalar, me arroja error de mcrypt, soy algo nuevo en esto
gracias por su ayuda

**Comment by jorgecancinof** [comment]
La última vez que probé el package fue el año 2018, con Laravel 5.5.

Lamentablemente entre el trabajo y estar enfocado en otros proyectos no me he dado el espacio de seguir manteniendo el package, por lo que no podría asegurarte si funciona correctamente en Laravel 6.

Me gustaría volver a dejarlo al día, pero no puedo prometer nada por ahora.

Saludos

**Comment by L3g4ult** [comment]
Muchas gracias por la respuesta
Espero puedas tener tiempo algún día de ver el package

Saludos
